// nuxt/app/components/SectionHeader.vue
<script lang="ts" setup>
    interface SectionHeaderProps{
        title: string;
    }

    const props = defineProps<SectionHeaderProps>();
</script>


<template>
    <div class="pb-8 flex gap-2">
        <div class="bg-[#FF6A33] w-1 h-auto"></div>
        <h2 class="text-3xl">{{props.title}}</h2>
    </div>
</template>

// next/components/common/SectionHeader.tsx
interface SectionHeaderProps{
    title:string;
}


export default function SectionHeader({title}:SectionHeaderProps){
    return(
        <div className="pb-8 flex gap-2">
            <div className="bg-[#FF6A33] w-1 h-auto"></div>
            <h2 className="text-3xl">{title}</h2>
        </div>
    )
}
