// next/components/Breadcrumb.tsx
import Link from "next/link";
import { Icon } from "@iconify/react";

interface BreadcrumbItem{
    name: string;
    path: string;
}
interface BreadcrmbProps{
    items:BreadcrumbItem[];
}

export const Breadcrumb = ({items} :BreadcrmbProps) =>{
    return(
         <nav aria-label="breadcrumb" className="pb-4">
            <ol className="flex items-center text-gray-500 gap-2">
                {items.map((item,index) =>(
                    <li key={index} className="flex items-center ">
                        {index > 0 &&(
                            <Icon icon="formkit:right" fontSize="24px"  className="text-gray-400"/>
                        )}

                        {index === items.length -1 ?(
                                <span className="text-[#FF6A33] font-semibold" aria-current="page">
                                    {item.name}
                                </span>
                            ):(
                                <Link href={item.path} className="hover:text-[#FF6A33] huver:underline transition-colors">
                                    { item.name }
                                </Link>
                            )
                        }
                    </li>
                ))}
            </ol>
        </nav>
    )
}

export default Breadcrumb

// nuxt/app/components/Breadcrumb.vue
<script setup lang="ts">
    interface BreadcrumbItem{
        name: string;
        path: string;
    }


    const props = defineProps<{
        items:BreadcrumbItem[];
    }>();
</script>

<template>
    <nav aria-label="breadcrumb" class="pb-4">
        <ol class="flex items-center text-gray-500 gap-2">
            <li v-for="(item,index) in items" :key="index" class="flex items-center ">
                <Icon v-if="index > 0" name="formkit:right" size="24px"  class="text-gray-400"/>
            
                <span v-if="index === items.length -1" class="text-[#FF6A33] font-semibold" aria-current="page">
                    {{item.name}}
                </span>

                <NuxtLink v-else :to="item.path" class="hover:text-[#FF6A33] huver:underline transition-colors">
                        {{ item.name }}
                </NuxtLink>
            </li>
        </ol>
    </nav>
</template>
