// next/components/common/Footer.tsx
import { Icon } from "@iconify/react";

export const Footer = () =>{
    return(
        <footer className="bg-[#2A2A2A] px-11 py-6 text-white">
            <div className="pb-9">
                <p className="text-[#FF6A33] text-2xl font-bold">Rikushop</p>
            </div>

            <hr className="border-t border-white" />

            <div className="flex gap-3 pt-9 justify-center items-center pb-3">
                <div className="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                    <Icon icon="pajamas:twitter" style={{ color: "white" }} width="24" height="24" />
                </div>
                <div className="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                <Icon icon="ri:facebook-fill" style={{ color: "white" }} width="24" height="24" />
                </div>

                <div className="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                    <Icon icon="mdi:instagram" style={{ color: "white" }} width="24" height="24" />
                </div>
            </div>
            <p className="text-center text-[12px]">Copyright © Rikushop. All Rights Reserved.</p>
        </footer>
    );
}

// nuxt/app/components/Footer.vue
<template>
    <footer class="bg-[#2A2A2A] px-11 py-6 text-white">
        <div class="pb-9">
            <p class="text-[#FF6A33] text-2xl font-bold">Rikushop</p>
        </div>

        <hr class="border-t border-white">

        <div class="flex gap-3 pt-9 justify-center items-center pb-3">
            <div class="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                <Icon name="pajamas:twitter" style="color: white" class="w-6 h-6" />
            </div>
            <div class="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                <Icon name="ri:facebook-fill" style="color: white" class="w-6 h-6" />
            </div>

            <div class="border border-white rounded-full w-10 h-10 flex items-center justify-center">
                <Icon name="mdi:instagram" class="w-7 h-7 text-white" />
            </div>
        </div>
        <p class="text-center text-[12px]">Copyright © Rikushop. All Rights Reserved.</p>
    </footer>
</template>
