// next/components/common/Header.tsx
"use client"

import {useState} from "react";
import { Icon } from "@iconify/react";
import { SearchBar } from "@/components/SearchBar";
import LoginDialog from "../dialog/LoginDialog";

export const Header = () =>{
    const [isOpenDialog,setIsOpenDialog] = useState(false);

    const toggle = () =>{
        setIsOpenDialog(!isOpenDialog);
    }

    return(
         <header className=" border-b border-gray-400 px-6 py-5">
            <div className="flex items-center justify-between pb-3 sm:pb-0">
                <div className="flex gap-4">
                    <p className="text-[#FF6A33] text-4xl font-bold">Rikushop</p>
                    <div className="hidden sm:flex">
                        <SearchBar />
                    </div>
                </div>
                <div className="flex items-center gap-2">
                    <p className="text-lg" onClick={toggle}>ログイン</p>
                    { isOpenDialog && <div className=" bg-black/20 fixed inset-0 z-10 " onClick={() => toggle()}><LoginDialog /></div> }
                    <Icon icon="mdi:cart" style={{ color: "#FF6A33" }} width="24px" height="24px" />
                </div>
            </div>
            <div className="sm:hidden">
                <SearchBar />
            </div>
        </header>
    )
}

export default Header;

// nuxt/app/components/Header.vue
<script lang="ts" setup>
    import LoginDialog from './Dialog/LoginDialog.vue';
    import {ref} from 'vue';
import SearchBar from './SearchBar.vue';

    const isOpenDialog = ref(false)

    const toggle = () => {
        isOpenDialog.value = !isOpenDialog.value
    }
</script>

<template>
    <header class=" border-b border-gray-400 px-6 py-5">
        <div class="flex items-center justify-between pb-3 sm:pb-0">
            <div class="flex gap-4">
                <p class="text-[#FF6A33] text-4xl font-bold">Rikushop</p>
                <div class="hidden sm:flex">
                    <SearchBar />
                </div>
            </div>
            <div class="flex items-center gap-2">
                <p class="text-lg" @click="toggle">ログイン</p>
                <LoginDialog v-if="isOpenDialog" @close="isOpenDialog = false"/>
                <Icon name="mdi:cart" style="color: #FF6A33" size="2em" />
            </div>
        </div>
        <div class="sm:hidden">
            <SearchBar />
        </div>
    </header>
</template>
