// nuxt/app/pages/products/index.vue
<script setup lang="ts">
    import type {Products} from '~/../types/index'
    import { ref } from 'vue';
import SectionHeader from '~/components/SectionHeader.vue';

    const {data,error} = useFetch<Products[]>("/api/products")

    //ページネーション管理
    const currentPage = ref<number>(1);
    const ITEM_PRE_PAGE = 24;

    //初めのページ
    const start = computed(() =>{
        return (currentPage.value -1) * ITEM_PRE_PAGE;
    });

    //最後のページ
    const end = computed(() =>{
        return start.value + ITEM_PRE_PAGE;
    });

    //合計ページ
    const total = computed(()=>{
        return Math.ceil(data.value?.length ?? 0) / ITEM_PRE_PAGE;
})
</script>

<template>
  <div class="min-h-screen">
        <section class="xl:max-w-5xl mx-auto px-4 py-16">
            <SectionHeader title="商品一覧" />
            <div class="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4 gap-6 pb-10">
                <ProductCard
                v-for="products in data?.slice(start,end)"
                :to="`/products/${products.id}`"
                :title="products.name"
                :image="products.image[0]?.img_path"
                :price="products.price" 
                :reviews="products._count.review" />
                </div>

                <div class="flex relative">
                
                <NuxtLink 
                    v-if="currentPage > 1" 
                    :to="`/products?page=${currentPage}`" 
                    class="absolute text-white text-center bg-[#FF6A33] px-8 py-2.5 left-0"
                >
                    <button @click="currentPage--">戻る</button>
                </NuxtLink>
                    <NuxtLink 
                    v-if=" currentPage < total"
                    :to="`/products?page=${currentPage}`" 
                    class="absolute text-white text-center bg-[#FF6A33] px-8 py-2.5 right-0"            
                >
                    <button @click="currentPage++">進む</button>
                </NuxtLink>
            </div>
        </section>
    </div>
</template>

// next/app/products/page.tsx
"use client"

import useProducts from "@/hooks/useProducts";
import { useSearchParams } from "next/navigation";
import ProductCard from "@/components/ProductCard";
import Link from "next/link";
import { useState } from "react";
import SectionHeader from "@/components/common/SectionHeader";


export default function Products(){
    const [page,setPage] = useState(1);
    const searchParams = useSearchParams()
    const ITEM_PER_PAGE = 24; 

    //useProduct使用
    const {data:productsData} = useProducts();
    if(!productsData) return <p>商品情報を取得できませんでした</p> 

    //ページネーション管理
    const start = (page -1) * ITEM_PER_PAGE; //最初のページ
    const end = start + ITEM_PER_PAGE; //最後ののページ
    const totalPage = (productsData?.data.length / ITEM_PER_PAGE);　//総ページ数


    return(
        <main>
            <div className="xl:max-w-5xl px-4 py-16 mx-auto">
                <SectionHeader title="商品一覧" />
                <section className="grid sm:grid-cols-3 lg:grid-cols-4 grid-cols-1 gap-4 ">
                    {productsData?.data.slice(start,end).map((product) =>{
                        return(
                            <Link key={product.name} href={`products/${product.id}`}>
                                <ProductCard title={product.name} price={product.price} reviews={product._count.Review} image={product.Image[0].img_path} />
                            </Link>
                        )
                    })}
                </section>
                <section className="relative py-4">
                    {!(page === 1) && 
                        <Link href={`products?page=${page}`} className=" absolute left-0">
                            <button className="bg-[#FF6A33] text-white px-2 py-1.5" onClick={() => setPage(page -1)}>
                                戻る
                            </button>
                        </Link>
                    }

                    {page === totalPage &&
                        <Link href={`products?page=${page}`} className=" absolute right-0">
                        <button className="bg-[#FF6A33] text-white px-2 py-1.5" onClick={() => setPage(page  + 1)}>
                            進む
                        </button>
                    </Link>
                    }
                </section>
            </div>
        </main>
    )
}
