// next/components/cart/ConfilmProduct.tsx
import Image from "next/image";

interface productCardProps{
    image?:string;
    title:string;
    price:number;
    quantity:number;
}
    

export const ConfilmProduct = ({image,title,price,quantity}:productCardProps) =>{
    return(
        <div className="flex justify-between items-center gap-6 w-full h-30">
        <div className="flex items-center">
                <div className="flex justify-center items-center bg-[#F2F1F1] w-30 h-30 rounded-2xl">
                    <Image src={`/products/${image}`} width="100" height="100" alt={title}/>
                </div>
                <div className="pl-3 md:pl-6 md:text-2xl">
                    <p className="font-medium pb-3">{title}</p>
                    <p className="font-bold">¥<span className="pl-1.5 text-[#FF6A33]">{price}</span></p>
                </div>
        </div>
            <p>数量：<span>{quantity}</span></p>
        </div>
    )
}

// nuxt/app/components/cart/ConfilmProduct.vue
<script lang="ts" setup>
    interface productCardProps{
        image?:string;
        title:string;
        price:number;
        quantity:number;
    }
    
    const props = defineProps<productCardProps>();

    const imagepath = "/products/" + props.image;   //画像パス
</script>

<template>
     <div class="flex justify-between items-center gap-6 w-full h-30">
       <div class="flex items-center">
            <div class="flex justify-center items-center bg-[#F2F1F1] w-30 h-30 rounded-2xl">
                <NuxtImg :src="imagepath" width="100" height="auto"/>
            </div>
            <div class="pl-3 md:pl-6 md:text-2xl">
                <p class="font-medium pb-3">{{title}}</p>
                <p class="font-bold">¥<span class="pl-1.5 text-[#FF6A33]">{{price}}</span></p>
            </div>
       </div>
        <p>数量：<span>{{quantity}}</span></p>
    </div>
</template>
