// next/app/products/[id]/review/page.tsx
"use client"

import SubmitButton from "@/components/submitButton"
import TextArea from "@/components/textArea"
import Breadcrumb from "@/components/Breadcrumb"
import { Icon } from "@iconify/react";
import { useState } from "react";
import { useParams, useRouter } from "next/navigation";
import useApi from "@/hooks/useApi";

export default function Review(){
    //レビュー状態管理
    const [reviewlevel,setReviewLevel] =useState<number>(5);
    const level:number[] = [1,2,3,4,5];
    const [description,setDescription] = useState<string>("");
    const route = useRouter();
    //商品ID取得
     const params = useParams();
     const productId = Number(params.id);


    const {fetchData} =useApi(`/api/review/${productId}`,"POST",true);

    //パンくずリスト
    const breadcrumb = [
        { name: '商品一覧', path: '/products' },
        { name: '商品詳細', path: `/products/${productId}` },
        { name: 'レビュー', path: `/products/${productId}/review` }
    ];

    const handleSubmit = async (e:React.ChangeEvent<HTMLElement>) =>{
        e.preventDefault();

        try{
            await fetchData({productId:productId,level:reviewlevel,description:description})
            route.push(`/products/${productId}`);
        }catch(error){
            console.error("レビューの送信に失敗しました:", error);
        }
    }

    return(
        <div>
            <section className="px-4 py-10 max-w-4xl mx-auto">
            <Breadcrumb items={breadcrumb} />
            <div  className="pb-8 flex gap-2">
                <div className="bg-[#FF6A33] w-1 h-auto"></div>
                <p className="text-3xl">レビューを投稿</p>   
            </div>
            <form onSubmit={handleSubmit}>
                <div>
                    <p>評価</p>
                    <div className="flex flex-row">
                        {level.map((n) =>(
                            <Icon key={n} onClick={() => setReviewLevel(n)}  icon={n  <= reviewlevel ? 'material-symbols:star-rounded' : 'material-symbols:star-outline-rounded'} style={{color:'gold',fontSize:'48px'}}/>    
                        ))}
                    </div>
                </div>
                <TextArea  onChange={(e) => setDescription(e.target.value)} label="レビュー" id="review" name="review"/>
                <SubmitButton value="投稿する" />
            </form>
        </section>
        </div>   
    )
}

// nuxt/app/pages/products/[id]/review.vue
<script setup lang="ts">
    import textArea from '~/components/textArea.vue';
    import submitButton from '~/components/submitButton.vue';
    import Breadcrumb from '~/components/Breadcrumb.vue';

    //リクエストデータ
    const level = ref(5);
    const description = ref("");

    //商品ID取得
    const route = useRoute();
    const productId = Number(route.params.id);

    const breadcrumb = [
        { name: '商品一覧', path: '/products' },
        { name: '商品詳細', path: `/products/${productId}` },
        { name: 'レビュー', path: `/products/${productId}/review` }
    ]
</script>

<template>
    <section class="px-4 py-10 max-w-4xl mx-auto">
        <Breadcrumb :items="breadcrumb"/>
        <div  class="pb-8 flex gap-2">
            <div class="bg-[#FF6A33] w-1 h-auto"></div>
            <p class="text-3xl">レビューを投稿</p>   
        </div>
        <div>
            <p>評価</p>
            <div class="flex flex-row">
                <Icon @click="level = n" v-for="n in 5" :name="n <= level? 'material-symbols:star-rounded' :'material-symbols:star-outline-rounded'" style="color: gold" size="48px" class=""/>    
            </div>
        </div>
        <textArea v-model="description" label="レビュー" id="review" name="review"/>
        <submitButton value="投稿する" :url="`/review/${productId}`" method="POST" :body="{level,description}" :redirectUrl="`/products/${productId}`" />
    </section>
</template>
